# Generated by Django 2.1.7 on 2019-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('B.T', 'B.Tech'), ('M.T', 'M.Tech'), ('B.B', 'BBA'), ('M.B', 'MBA'), ('B.S', 'Basic Science'), ('L', 'Law')], max_length=6)),
                ('year', models.IntegerField()),
                ('srn', models.CharField(max_length=14)),
                ('gname', models.CharField(max_length=20)),
                ('gaddress', models.TextField()),
                ('gmobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
