# Generated by Django 2.1.7 on 2019-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
