# Generated by Django 2.1.7 on 2019-04-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_registration_registered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registered_date',
        ),
    ]
