# Generated by Django 2.1.7 on 2019-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_complaint_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='parent_name',
            field=models.CharField(default='DEFAULT STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='whereto',
            field=models.CharField(choices=[('LG', 'LG'), ('P', 'PARENT'), ('O', 'OTHER')], default='DEFAULT STRING', max_length=3),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='room_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='arriving_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leaving_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
