# Generated by Django 2.1.7 on 2019-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190419_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='whereto',
            field=models.CharField(choices=[('LG', 'LG'), ('P', 'PARENT'), ('O', 'OTHER')], max_length=3),
        ),
    ]
