# Generated by Django 2.1.7 on 2019-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190419_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='block',
            field=models.CharField(choices=[('N.B', 'NEW BLOCK'), ('N.B.X', 'NBX'), ('M.B', 'MESS BLOCK'), ('M.M', 'MM'), ('I.T', 'IT'), ('I.H', 'IH')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='block',
            field=models.CharField(choices=[('N.B', 'NEW BLOCK'), ('N.B.X', 'NBX'), ('M.B', 'MESS BLOCK'), ('M.M', 'MM'), ('I.T', 'IT'), ('I.H', 'IH')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='whereto',
            field=models.CharField(choices=[('LG', 'LG'), ('P', 'PARENT'), ('O', 'OTHER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.CharField(choices=[('B.T', 'B.Tech'), ('M.T', 'M.Tech'), ('B.B', 'BBA'), ('M.B', 'MBA'), ('B.S', 'Basic Science'), ('L', 'Law')], max_length=20),
        ),
    ]
